//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis_ise.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }
        [Display(Name ="Departman Adý")]
        public Nullable<int> DepartmanId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<byte> Yas { get; set; }
        [Display(Name ="Maaþ")]
        public Nullable<short> Mass { get; set; }
        [Display(Name = "Doðum Tarihi")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        [Display(Name = "Medeni Durumu")]
        public bool Evlimi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
