//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis_ise.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        [Display(Name = "Personel Id")]
        public int Id { get; set; }
        [Display(Name ="Departman Adý")]
        [Required(ErrorMessage = "Departman Adý zorunludur!")]

        public Nullable<int> DepartmanId { get; set; }
        [Required(ErrorMessage = "Ad zorunludur!")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyad zorunludur!")]
        public string Soyad { get; set; }
        [Display(Name = "Yaþ")]
        [Required(ErrorMessage = "Yaþ zorunludur!")]
        public Nullable<byte> Yas { get; set; }
        [Display(Name ="Maaþ")]
        [Required(ErrorMessage = "Maþþ zorunludur!")]
        public Nullable<short> Mass { get; set; }
        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Doðum tarihi zorunludur!")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        [Required(ErrorMessage = "Cinsiyet zorunludur!")]
        public bool Cinsiyet { get; set; }
        [Display(Name = "Medeni Durumu")]
        [Required(ErrorMessage = "Medeni durum zorunludur!")]
        public bool Evlimi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
